// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: LayoutProps<"/">) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }



// ------------------------------------------------------------------------------------



// import type { Metadata } from 'next';
// import './globals.css';

// import Navbar from '../components/layout/navbar';
// import Sidebar from '../components/layout/sidebar';

// export const metadata: Metadata = {
//   title: 'Contact Information',
//   description:
//     'Customer intelligence and management platform',
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body>
//         <div className="min-h-screen bg-[#f6f8fc]">
//           <Sidebar />

//           <div className="lg:ml-[260px]">
//             <Navbar />

//             <main className="min-h-[calc(100vh-72px)] p-4 sm:p-6 lg:p-8">
//               {children}
//             </main>
//           </div>
//         </div>
//       </body>
//     </html>
//   );
// }




import type { Metadata } from 'next';

import './globals.css';

import AppShell from '@/components/layout/app-shell';

export const metadata: Metadata = {
  title:
    'ContactIQ - Customer Intelligence',
  description:
    'Manage customers, products, services and follow-ups.',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
